install.packages("MASS")
library(MASS)
attach(Boston)
?Boston
head(Boston)
dim(Boston)
names(Boston)
str(Boston)
nrow(Boston)
ncol(Boston)
summary(Boston)
summary(Boston$crim)

install.packages("ISLR")
library(ISLR)
data("Auto")
head(Auto)
help("Auto")
head(Auto, 10)
names(Auto)
summary(Auto)
fivenum(Auto$mpg)
boxplot(Auto$weight)
mean(Auto$weight)
median(Auto$weight)

help("read.csv")
data1 <- read.csv(file.choose(), head = TRUE)
head(data1)
summary(data1$EPI)
boxplot(data1$EPI)
fivenum(data1$EPI, na.rm = TRUE)
hist(data1$EPI)
